---
version: "1.1.2"
slug: coturn
name: Coturn
description: TURN/STUN server for WebRTC remote camera relay
url: https://github.com/rwjack/addons
arch:
  - aarch64
  - amd64
startup: services
boot: manual
init: false
host_network: true
map:
  - ssl
options:
  username: turnuser
  password: ""
  realm: turn.local
  listening_ip: ""
  external_ip: ""
  min_port: 48000
  max_port: 49000
  use_tls: false
  tls_listening_port: 5349
  turn_domain: ""
  cert_file: fullchain.pem
  key_file: privkey.pem
  log_level: info
schema:
  username: str
  password: password
  realm: str
  listening_ip: str
  external_ip: str
  min_port: int
  max_port: int
  use_tls: bool
  tls_listening_port: int
  turn_domain: str?
  cert_file: str
  key_file: str
  log_level: list(info|verbose|debug)
